server:
  port: 8880

spring:
    datasource:
        name: test
        #url: jdbc:mysql://119.23.130.199:3306/power2
        #username: etl
        #password: immotor!99
        url: jdbc:mysql://rm-wz99y4784rwj1w48txo.mysql.rds.aliyuncs.com:3306/immotordata
        username: immotor_biddata
        password: immotor!99
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.immotor.bigdata.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
    level:
        com.immotor.bigdata.mapper: DEBUG